# Generated by Django 2.0.6 on 2018-07-12 05:27

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
